"""create request lifecycle tables

Revision ID: 7b9bc6f77f01
Revises:
Create Date: 2026-07-27 02:43:03.928736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9bc6f77f01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_employee_id', sa.String(length=32), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('tier', sa.Enum('T0', 'T1', 'T2', name='autonomy_tier'), nullable=True),
    sa.Column('status', sa.Enum('received', 'classifying', 'in_progress', 'awaiting_approval', 'approved', 'rejected', 'completed', 'failed', name='request_status'), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_requester_employee_id'), 'requests', ['requester_employee_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_thread_id'), 'requests', ['thread_id'], unique=False)
    op.create_index(op.f('ix_requests_tier'), 'requests', ['tier'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'changes_requested', name='approval_decision'), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_request_id'), 'approvals', ['request_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('agent', 'human', 'system', name='actor_type'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_events_request_time', 'audit_events', ['request_id', 'occurred_at'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('response_letter', 'audit_bundle', name='document_kind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_content_hash'), 'generated_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_generated_documents_request_id'), 'generated_documents', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_request_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_content_hash'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('ix_audit_events_request_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_request_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_requests_tier'), table_name='requests')
    op.drop_index(op.f('ix_requests_thread_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_requester_employee_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
